DROP TABLE IF EXISTS arrivalTime;
create table arrivalTime(ID INT, arrivalTime FLOAT, source TEXT, statement INT);
insert into arrivalTime(ID, arrivalTime, source, statement) values(1, -4.719, 'find',1);
insert into arrivalTime(ID, arrivalTime, source, statement) values(2, -4.719, 'find',2);
insert into arrivalTime(ID, arrivalTime, source, statement) values(3, -4.719, 'find',3);
insert into arrivalTime(ID, arrivalTime, source, statement) values(4, -7.043, 'find',4);
insert into arrivalTime(ID, arrivalTime, source, statement) values(5, -3.943, 'find',5);
insert into arrivalTime(ID, arrivalTime, source, statement) values(6, -4.719, 'find',6);
insert into arrivalTime(ID, arrivalTime, source, statement) values(7, -4.719, 'find',7);
insert into arrivalTime(ID, arrivalTime, source, statement) values(8, -4.719, 'find',8);
insert into arrivalTime(ID, arrivalTime, source, statement) values(9, -4.719, 'find',9);
insert into arrivalTime(ID, arrivalTime, source, statement) values(10, -4.686, 'find',10);
insert into arrivalTime(ID, arrivalTime, source, statement) values(11, -6.125, 'find',11);
insert into arrivalTime(ID, arrivalTime, source, statement) values(12, -4.719, 'find',12);
insert into arrivalTime(ID, arrivalTime, source, statement) values(13, -3.955, 'find',13);
insert into arrivalTime(ID, arrivalTime, source, statement) values(14, -3.955, 'find',14);
SELECT * FROM arrivalTime;